---
- name: start ssh.socket
  systemd:
    name: ssh.socket
    state: started
    enabled: true
    daemon_reload: true
  become: true

- name: stop ssh.service
  systemd:
    name: ssh.service
    state: stopped
    enabled: false
  systemd: true
